---
# tasks file for roles/docker_install
- name: Debian docker install
  import_tasks: debian.yml
  when: ansible_os_family|lower == 'debian'

- name: Docker-compose install
  import_tasks: docker-compose.yaml