- name: Install ZIP
  apt:
    name: zip
    update_cache: yes

- name: Get Terrafrom archive
  get_url:
    url: "{{ terraform_url }}"
    dest: "{{ terraform_archive }}"
    mode: 0755

- name: Unzip to destiantion
  unarchive:
    src: "{{ terraform_archive }}"
    dest: "{{ terraform_path }}"
    remote_src: yes
    mode: 0755